### PR TITLE
Clean up uswds-jekyll includes and touch up styling

### PR DESCRIPTION
**Pull request by igorkorenfeld**
# Pull request summary
This PR is another follow-on to #9 and cleans up some of the unused styles and includes after detaching from uswds-jekyll. The intent was to flatten some of the re-direction and abstraction that was necessary for theme, but is less helpful to us in our customized site. As such includes that were previously nested in folders have been moved to the main includes folder, and options that were present in constructing the header were removed in favor of directly implementing the header we have designed. This PR also cleans up a few styling errors such as footer spacing on smaller screens. 

👓 [Preview](https://federalist-c9d7d8a7-acd7-479e-9ab8-60987473d2d0.sites.pages.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/ik/clean-up-3/)

### CODE REVIEW

**Review by echappen — COMMENTED** [review]
[blocking bug] I’m still reviewing all of the changes, but wanted to highlight a few initial things:

1. USA Banner doesn’t expand when clicking “Here’s how you know” text / down caret
2. Can’t get the menu to expand in tablet/mobile when clicking the “Menu” button

I need to do more digging to find out the reasons, but we’re missing either some essential script or some markup. May have been removed in this PR or the previous. 

For the menu, the "is-visible" class isn't getting added to the "usa-nav" element when clicking the menu button, which leads me to believe that it's missing JS.

**Comment by igorkorenfeld** [comment]
Great catch! I change the way the script were loading and I think that broke it.

**Comment by igorkorenfeld** [comment]
@echappen that bug should hopefully be fixed now

**Review by echappen — APPROVED** [review]
LGTM—great job, Igor!

**Pull request merged**
